include_guard(GLOBAL)

function(petstory_detect_apple_platform OUT_PLATFORM OUT_IS_IOS)
    set(platform_name "")
    set(is_ios FALSE)

    if(APPLE)
        if(DEFINED O2_PLATFORM)
            if(O2_PLATFORM STREQUAL "iOS")
                set(platform_name "iOS")
                set(is_ios TRUE)
            elseif(O2_PLATFORM STREQUAL "Mac")
                set(platform_name "Mac")
            endif()
        endif()

        if(NOT platform_name)
            if(CMAKE_SYSTEM_NAME STREQUAL "iOS")
                set(platform_name "iOS")
                set(is_ios TRUE)
            elseif(DEFINED CMAKE_OSX_SYSROOT AND NOT CMAKE_OSX_SYSROOT STREQUAL "")
                string(TOLOWER "${CMAKE_OSX_SYSROOT}" osx_sysroot_lower)
                if(osx_sysroot_lower MATCHES "iphone")
                    set(platform_name "iOS")
                    set(is_ios TRUE)
                else()
                    set(platform_name "Mac")
                endif()
            else()
                set(platform_name "Mac")
            endif()
        endif()
    endif()

    set(${OUT_PLATFORM} "${platform_name}" PARENT_SCOPE)
    set(${OUT_IS_IOS} ${is_ios} PARENT_SCOPE)
endfunction()

function(petstory_apply_ios_build_defaults)
    set(O2_TESTS OFF CACHE BOOL "Enables o2 tests with Google Test" FORCE)
    set(O2_EDITOR ON CACHE BOOL "Enables o2 editor." FORCE)

    if(NOT CMAKE_OSX_ARCHITECTURES)
        set(CMAKE_OSX_ARCHITECTURES "${CMAKE_HOST_SYSTEM_PROCESSOR}" CACHE STRING "iOS simulator architectures" FORCE)
    endif()
endfunction()

function(petstory_set_host_tool_paths ROOT_DIR O2_DIR OUT_CODE_TOOL OUT_ASSETS_BUILDER)
    set(${OUT_CODE_TOOL} "${O2_DIR}/CodeTool/Bin/o2CodeTool" PARENT_SCOPE)
    set(${OUT_ASSETS_BUILDER} "${ROOT_DIR}/Bin/Mac/AssetsBuilder" PARENT_SCOPE)
endfunction()