name: Linux clang

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: recursive 

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y \
          build-essential \
          cmake \
          libgl1-mesa-dev \
          libglu1-mesa-dev

    - name: Build with CMake
      run: |
        mkdir -p build
        cd build
        cmake ..
        make
