name: Windows CMake

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Build PetStory
            target: PetStory
            o2_editor: OFF
            o2_tests: OFF
            run_ctest: false
          - name: Build Editor
            target: Editor
            o2_editor: ON
            o2_tests: OFF
            run_ctest: false
          - name: Build o2Tests
            target: o2Tests
            o2_editor: OFF
            o2_tests: ON
            run_ctest: true

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: recursive 

    - name: Set up Visual Studio
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Configure CMake
      run: cmake -S . -B build -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=Release -DO2_TESTS=${{ matrix.o2_tests }} -DO2_EDITOR=${{ matrix.o2_editor }} -DO2_MSVC_MP_COUNT=0

    - name: Build with CMake
      run: cmake --build build --config Release --parallel 1 --target ${{ matrix.target }}

    - name: Run o2Tests
      if: matrix.run_ctest
      run: ctest --test-dir build --build-config Release --output-on-failure
